Porting code for moby/buildkit to run in darwin
1) bypass moby/buildkit/util/leaseutil
   - build error was:
      ../../vendor/github.com/moby/buildkit/util/leaseutil/manager.go:33:16: cannot use &local literal (type *local) as type leases.Manager in return argument:
	 *local does not implement leases.Manager (missing AddResource method)

2) During the bump of containerd specconv_linux.go gets deleted
    - vendor/github.com/moby/buildkit/util/rootless/specconv/specconv_linux.go

Fix moby/buildkit/util/entitlements because WithInsecureSpec() darwin doesn't support

Introduced a stub function WithInsecureSpec() since seccomp is a linux
specific feature.

Build error:

vendor/github.com/moby/buildkit/executor/oci/spec_unix.go:53:23: undefined: entitlements.WithInsecureSpec

Dirty commit: bypass build constraints for executor

there must be a better way to do this with in the context of dockerd daemon

Build error:

- vendor/github.com/moby/buildkit/executor/oci/spec_unix.go:11:2: build constraints exclude all Go files in /Users/aniketh/go/src/github.com/docker/docker/vendor/github.com/containerd/containerd/contrib/seccomp
- vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go:27:2: build constraints exclude all Go files in /Users/aniketh/go/src/github.com/docker/docker/vendor/github.com/moby/buildkit/util/rootless/specconv

Fix buildkit because Unmount() syscall on darwin does not support MNT_DETACH

The build error was:
vendor/github.com/moby/buildkit/snapshot/localmounter_unix.go:17:38: undefined: syscall.MNT_DETACH