port for docker/daemon package
Features contained in this patch:

    - port of daemon/update
    - Added stub stats to daemon/daemon_darwin.go
    - Introduced few stub functions for setupResolvConf(), cleanupMounts(), cleanupMountsByID(), getRealPath(), getPluginExecRoot() into daemon_darwin.go
    - Introduced volumes
    - Introduced container_darwin
    - Expose exec functions to darwin
    - Introduced daemon/inspect_darwin
    - expose daemon/images to darwin
    - expose daemon/reload
    - expose daemon/list
    - Fix in daemon/config: undefined: BridgeConfig
    - Exposed listeners functions for darwin: this aspect of the code is the initial point on how docker client establishes communication with the daemon. Exposing different socket listeners eg: unix, tcp and fd.
    - Introduced container_operations_linux and container_operations_unix
        *  decoupling the function to _linux.go for linux syscall specific errors such as unix.MS_NOEXEC.
    - Port for deamon_unix: Splitted the daemon_unix code to daemon_linux to hide from newly created daemon_darwin
    - Ignore system configured container config options: RuncOptions and CreateOptions
        * Both of these are protobuf gererated APIs to handle runc specific configurations in dockerd
        * Currently, we are ignoring to set the system set configuration to create the container. I believe better workaround would be to expose similar configuration options with in runu to containerd so that we are able to let containerd configure it's own containers
    - contains fix for the build error:
                daemon/start.go:164:11: daemon.saveApparmorConfig undefined (type *Daemon has no field or method saveApparmorConfig)
                daemon/container_operations_unix.go:147:14: undefined: unix.Mount
                daemon/container_operations_unix.go:147:58: undefined: unix.MS_NOEXEC
                daemon/container_operations_unix.go:147:73: undefined: unix.MS_NOSUID
                daemon/container_operations_unix.go:147:88: undefined: unix.MS_NODEV
                daemon/daemon_unix.go:1395:13: cs.Read undefined (type *"github.com/docker/docker/libcontainerd/types".Stats has no field or method Read)
                daemon/daemon_unix.go:1396:13: cs.Metrics undefined (type *"github.com/docker/docker/libcontainerd/types".Stats has no field or method Metrics)
                daemon/daemon_unix.go:1571:20: undefined: "github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/cgroups".FindCgroupMountpointAndRoot