Port of OCI features required and daemon/daemon_unix for docker engine in darwin
Features contained in this commit:

    - Enable docker run: lfill the ociSpec and hence locate rootfs
    - exposed functions getSourceMount(), hasMountinfoOption() to darwin and made stand alone from oci_linux.go

        build errors that were fixed:
           *  daemon/daemon_unix.go:1278:35: undefined: getSourceMount
           * daemon/daemon_unix.go:1294:5: undefined: hasMountinfoOption
           * daemon/daemon_unix.go:1294:33: undefined: sharedPropagationOption
           * daemon/daemon_unix.go:1294:58: undefined: slavePropagationOption

    - Added mergeUlimits()